services:
  # Backend
  - type: web
    name: whaticket-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npx sequelize db:migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIALECT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: whaticket-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

  # Frontend
  - type: web
    name: whaticket-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build

databases:
  - name: whaticket-db
    plan: free
    region: oregon
